### ISSUE TITLE
Abstra Cloud Deploy

### ISSUE THREAD

**Issue by Nkluge-correa** [abstra-app/abstra-lib#5]
Hello!

I have been trying to launch a project that I built with `abstra` (a great library, by the way) on the `Abstra Cloud`, but I cannot make it work. My cloud console does not even show that a deployment was attempted.

Here is the structure of my current folder:

```lua
--main_folder
      --.abstra
         --credentials
      --img
         --logo_icon.ico
      --questions
         --question0.yaml
         --question1.yaml
         --question2.yaml
         --question3.yaml
         --question4.yaml
         --question5.yaml
      --abstraignore
      --abstra.json
      --AIA.py
      --glossary.md
      --requirements.txt
``` 

The app works fine in my machine.

I followed the tutorial on YouTube, but following the same steps did not produce those results. Is there another way to deploy `abstra` forms (not using their own Cloud service)? I would appreciate it if anyone can help! I want to be able to deploy this, and I don't want to have to write the entire thing again on some other framework like `Streamlit` or `Django`.

**Comment by brunovcosta** [comment]
Hey @Nkluge-correa, thank you for reporting. I'm closing this issue since it was solved in the equivalent [discord channel thread](https://discord.com/channels/1065692759501054084/1072238076962807888/1162071710556749967)

**Comment by Nkluge-correa** [comment]
Completely solved. Thank you for the quick response!
