### ISSUE TITLE
Check list widget does not becomes required

### ISSUE THREAD

**Issue by Nkluge-correa** [abstra-app/abstra-lib#6]
I was following the code example at the [documentation](https://docs.abstra.io/widgets/checklist-input):

```python
af.Page().read_checklist(
    "",
    [
        {
            "label": "I have read and agree to the [terms of services](https://example.com)",
            "value": "agree",
        },
    ],
    required=True,
).run()
```

But I cannot make the input field become required like it happens with other widgets (e.g., [`read_cards`](https://docs.abstra.io/widgets/cards-input)). Even if I do not mark anything, the page goes to the next slide. Is the required condition on `read_checklist` broken?

**Comment by lucasrrt** [comment]
Hey @Nkluge-correa, in version [v1.27.9](https://github.com/abstra-app/abstra-lib/tree/v1.27.9) we added two properties to `read_checklist`, `min` and `max`, that control the number of options the user must and can select.

For your example, you can do:
```python
af.Page().read_checklist(
    "",
    [
        {
            "label": "I have read and agree to the [terms of services](https://example.com)",
            "value": "agree",
        },
    ],
    required=True, # default is True, so this is not necessary, but you can leave it to make it clear
    min=1,
).run()
```

The user will have to check the box to proceed with the form.

You can update the lib with `pip install abstra --upgrade`
